- exercise: Analisi Spettrale IASI
  settings: spectral_analysis/tabSettings.yaml
  image: IASI.jpg
  defaults:
    - id: ParametriTab
      values:
        EditBande: "645.0,800.0; 800.0, 980.0; 980.0, 1080.0; 1210.0, 1600.0; 2100.0, 2250.0"
        CampoFov: 1
        MenuTerreno: Terra
        CampoNubi: 10
  inputs:
    - name: bande_selezionate_str
      tab: ParametriTab
      component: EditBande
    - name: fov_selezionato
      tab: ParametriTab
      component: CampoFov
    - name: terreno_selezionato
      tab: ParametriTab
      component: MenuTerreno
    - name: nubi_max
      tab: ParametriTab
      component: CampoNubi
  pipeline: spectral_analysis/pipeline.yaml
  resultText: "['Rapporto bonus calcolato: ', num2str(rapporto_bonus)]"
  resultTextInterpreter: 'none'