- name: Parametri Spettrali
  id: ParametriTab
  components:
    - kind: uidropdown
      id: MenuGas
      labels:
        - text: Composto Gas
          position: left
      Items:
        - N2O
    - kind: uispinner
      id: CampoFov
      labels:
        - text: Field of View (FoV)
          position: left
      Step: 1
      Limits: [1, 120]
    - kind: uidropdown
      id: MenuTerreno
      labels:
        - text: Tipo di Terreno
          position: left
      Items:
        - Terra
        - Mare
    - kind: uispinner
      id: CampoNubi
      labels:
        - text: Nuvolosità Massima
          position: left
        - text: "%"
          position: right
      Step: 1
      Limits: [0, 100]
